# Generated by Django 3.2.8 on 2021-12-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('related_suspects', models.ManyToManyField(related_name='_core_suspect_related_suspects_+', to='core.Suspect')),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=55)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('arms', models.ManyToManyField(to='core.Arm')),
                ('crimes', models.ManyToManyField(related_name='_core_crime_crimes_+', to='core.Crime')),
                ('suspects', models.ManyToManyField(to='core.Suspect')),
            ],
        ),
    ]
