# Generated by Django 3.2.8 on 2021-12-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='arms',
            field=models.ManyToManyField(blank=True, to='core.Arm'),
        ),
        migrations.AlterField(
            model_name='crime',
            name='suspects',
            field=models.ManyToManyField(blank=True, to='core.Suspect'),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='related_suspects',
            field=models.ManyToManyField(blank=True, related_name='_core_suspect_related_suspects_+', to='core.Suspect'),
        ),
    ]
