# Generated by Django 3.2.8 on 2021-12-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211214_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='crimes',
            field=models.ManyToManyField(blank=True, related_name='_core_crime_crimes_+', to='core.Crime'),
        ),
    ]
