# Generated by Django 3.2.8 on 2021-12-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_crime_crimes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='crimes',
        ),
        migrations.AddField(
            model_name='crime',
            name='related_crimes',
            field=models.ManyToManyField(blank=True, related_name='_core_crime_related_crimes_+', to='core.Crime'),
        ),
    ]
